mod paths;

use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
use utoipa::{Modify, OpenApi};

use crate::dto::memories::MemoryTypeResponse;
use crate::dto::{
    AddMemoryRequest, AddMemoryResponse, AdminOrgMemoryEventItemResponse, ApiKeyItemResponse,
    ApiKeyScopeResponse, ApplyBackgroundJobRunRetentionRequest,
    ApplyBackgroundJobRunRetentionResponse, ApplyBackgroundJobRunRetentionSummaryResponse,
    ApplyProviderUsageRetentionRequest, ApplyProviderUsageRetentionResponse,
    ApplyProviderUsageRetentionSummaryResponse, ApplyRetentionRequest, ApplyRetentionResponse,
    ApplyRetentionSummaryResponse, BackgroundJobDefinitionResponse,
    BackgroundJobLockStatusResponse, BackgroundJobRunResponse, BackgroundJobSnapshotResponse,
    BackgroundJobsResponse, BuildContextRequest, BuildContextResponse, ContextBudgetResponse,
    ContextCacheMetricsBodyResponse, ContextCacheMetricsResponse, ContextCacheResponse,
    ContextCompressionResponse, ContextMemoryResponse, CreateApiKeyRequest, CreateApiKeyResponse,
    CreateMemoryUsageSnapshotRequest, CreateMemoryUsageSnapshotResponse, DeleteMemoryResponse,
    DeleteOrgPlanResponse, ExportFactItemResponse, ExportMemorySourceResponse, ExportUserResponse,
    ForgetUserResponse, GetOrgPlanResponse, ImportUserDataRequest, ImportUserDataResponse,
    ImportUserDataSummaryResponse, ImportValidationIssueResponse, ImportValidationSummaryResponse,
    ListApiKeysResponse, ListMemoriesResponse, ListMemoryEventsResponse, ListMemoryItemResponse,
    ListOrgUsersResponse, MemoryEventItemResponse, MemoryEventOperationResponse,
    MemoryItemResponse, MemoryMessageRequest, MemoryOperationSummaryResponse,
    MemoryUsageLatestSnapshotResponse, MemoryUsageSnapshotResponse, OrgMemoryUsageSummaryResponse,
    OrgPlanLimitsResponse, OrgPlanResponse, OrgQuotaLimitsResponse, OrgQuotaStatusBodyResponse,
    OrgQuotaStatusResponse, OrgQuotaUsageResponse, OrgSummaryBodyResponse, OrgSummaryResponse,
    OrgUsageDashboardBodyResponse, OrgUsageDashboardResponse, OrgUsageDateRangeQuery,
    OrgUserSummaryResponse, ProviderUsageDailyBodyResponse, ProviderUsageDailyBucketResponse,
    ProviderUsageDailyQueryParams, ProviderUsageDailyResponse, ProviderUsageEventItemResponse,
    ProviderUsageQueryParams, ProviderUsageResponse, ProviderUsageSummaryResponse,
    QueryBackgroundJobRunsParams, QueryBackgroundJobRunsResponse, QueryMemoryUsageSnapshotsParams,
    QueryMemoryUsageSnapshotsResponse, QuotaViolationResponse, RevokeApiKeyResponse,
    RunBackgroundJobResponse, SearchMemoryFiltersRequest, SearchMemoryRequest,
    SearchMemoryResponse, SearchMemoryResultResponse, SearchOrgMemoryEventsResponse,
    UpsertOrgPlanLimitsRequest, UpsertOrgPlanRequest, UpsertOrgPlanResponse,
    UserMemoryExportResponse,
};
use crate::response::{ErrorBody, ErrorDetail};
use crate::routes::health::{HealthResponse, ReadyResponse, VersionInfo, VersionResponse};

/// OpenAPI document for the memcore HTTP API.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "memcore API",
        version = env!("CARGO_PKG_VERSION"),
        description = "Production-grade long-term memory engine for AI agents. \
            Protected routes require `Authorization: Bearer <api_key>` and `X-Organization-ID`. \
            `MEMCORE_AUTH_MODE=dev` accepts `MEMCORE_DEV_API_KEY` for local development without scope checks."
    ),
    paths(
        paths::health,
        paths::ready,
        paths::metrics,
        paths::version,
        paths::add_memory,
        paths::search_memory,
        paths::build_context,
        paths::list_user_memories,
        paths::delete_user_memory,
        paths::export_user_data,
        paths::import_user_data,
        paths::apply_retention,
        paths::forget_user,
        paths::list_user_memory_events,
        paths::create_api_key,
        paths::list_api_keys,
        paths::revoke_api_key,
        paths::get_org_summary,
        paths::get_background_jobs,
        paths::query_background_job_runs,
        paths::apply_background_job_run_retention,
        paths::run_background_job,
        paths::list_org_users,
        paths::search_org_memory_events,
        paths::get_context_cache_metrics,
        paths::get_org_quotas,
        paths::get_org_plan,
        paths::upsert_org_plan,
        paths::delete_org_plan,
        paths::get_provider_usage,
        paths::get_org_usage_dashboard,
        paths::create_memory_usage_snapshot,
        paths::query_memory_usage_snapshots,
        paths::get_provider_usage_daily,
        paths::apply_provider_usage_retention,
    ),
    components(schemas(
        ErrorBody,
        ErrorDetail,
        HealthResponse,
        ReadyResponse,
        VersionResponse,
        VersionInfo,
        AddMemoryRequest,
        MemoryMessageRequest,
        AddMemoryResponse,
        MemoryOperationSummaryResponse,
        MemoryItemResponse,
        MemoryTypeResponse,
        SearchMemoryRequest,
        SearchMemoryFiltersRequest,
        SearchMemoryResponse,
        SearchMemoryResultResponse,
        ListMemoriesResponse,
        ListMemoryItemResponse,
        DeleteMemoryResponse,
        ForgetUserResponse,
        ExportUserResponse,
        UserMemoryExportResponse,
        ExportFactItemResponse,
        ExportMemorySourceResponse,
        ImportUserDataRequest,
        ImportUserDataResponse,
        ImportUserDataSummaryResponse,
        ImportValidationIssueResponse,
        ImportValidationSummaryResponse,
        ApplyRetentionRequest,
        ApplyRetentionResponse,
        ApplyRetentionSummaryResponse,
        BuildContextRequest,
        BuildContextResponse,
        ContextBudgetResponse,
        ContextCompressionResponse,
        ContextCacheResponse,
        ContextMemoryResponse,
        ListMemoryEventsResponse,
        MemoryEventItemResponse,
        MemoryEventOperationResponse,
        CreateApiKeyRequest,
        CreateApiKeyResponse,
        ApiKeyItemResponse,
        ApiKeyScopeResponse,
        ListApiKeysResponse,
        RevokeApiKeyResponse,
        OrgSummaryResponse,
        OrgSummaryBodyResponse,
        BackgroundJobsResponse,
        BackgroundJobSnapshotResponse,
        BackgroundJobDefinitionResponse,
        BackgroundJobLockStatusResponse,
        BackgroundJobRunResponse,
        QueryBackgroundJobRunsParams,
        QueryBackgroundJobRunsResponse,
        ApplyBackgroundJobRunRetentionRequest,
        ApplyBackgroundJobRunRetentionResponse,
        ApplyBackgroundJobRunRetentionSummaryResponse,
        RunBackgroundJobResponse,
        ListOrgUsersResponse,
        OrgUserSummaryResponse,
        SearchOrgMemoryEventsResponse,
        AdminOrgMemoryEventItemResponse,
        ContextCacheMetricsResponse,
        ContextCacheMetricsBodyResponse,
        OrgQuotaStatusResponse,
        OrgQuotaStatusBodyResponse,
        OrgQuotaLimitsResponse,
        OrgQuotaUsageResponse,
        QuotaViolationResponse,
        OrgUsageDashboardResponse,
        OrgUsageDashboardBodyResponse,
        OrgUsageDateRangeQuery,
        OrgMemoryUsageSummaryResponse,
        MemoryUsageLatestSnapshotResponse,
        CreateMemoryUsageSnapshotRequest,
        CreateMemoryUsageSnapshotResponse,
        QueryMemoryUsageSnapshotsParams,
        QueryMemoryUsageSnapshotsResponse,
        MemoryUsageSnapshotResponse,
        ProviderUsageDailyResponse,
        ProviderUsageDailyBodyResponse,
        ProviderUsageDailyBucketResponse,
        ProviderUsageDailyQueryParams,
        OrgPlanResponse,
        OrgPlanLimitsResponse,
        GetOrgPlanResponse,
        UpsertOrgPlanRequest,
        UpsertOrgPlanLimitsRequest,
        UpsertOrgPlanResponse,
        DeleteOrgPlanResponse,
        ProviderUsageResponse,
        ProviderUsageSummaryResponse,
        ProviderUsageEventItemResponse,
        ProviderUsageQueryParams,
        ApplyProviderUsageRetentionRequest,
        ApplyProviderUsageRetentionResponse,
        ApplyProviderUsageRetentionSummaryResponse,
    )),
    tags(
        (name = "Health", description = "Liveness and readiness probes"),
        (name = "Metrics", description = "Prometheus scrape endpoint (disabled by default; auth required by default)"),
        (name = "Memories", description = "Memory lifecycle and search"),
        (name = "Context", description = "Context assembly for LLM prompts"),
        (name = "Users", description = "User-scoped data management"),
        (name = "Memory Events", description = "User-scoped memory audit events"),
        (name = "API Keys", description = "Organization API key management"),
        (name = "Admin", description = "Organization-level admin read endpoints"),
    ),
    modifiers(&SecurityAddon),
)]
pub struct ApiDoc;

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let Some(components) = openapi.components.as_mut() else {
            return;
        };

        components.add_security_scheme(
            "BearerAuth",
            SecurityScheme::Http(
                HttpBuilder::new()
                    .scheme(HttpAuthScheme::Bearer)
                    .bearer_format("API key")
                    .description(Some(
                        "Bearer API key. In dev mode use MEMCORE_DEV_API_KEY; in database mode use a stored key hash lookup.",
                    ))
                    .build(),
            ),
        );
    }
}
