ALTER TABLE background_job_runs
ADD COLUMN IF NOT EXISTS attempt_count INTEGER NOT NULL DEFAULT 1;

ALTER TABLE background_job_runs
ADD COLUMN IF NOT EXISTS max_attempts INTEGER NOT NULL DEFAULT 1;

ALTER TABLE background_job_runs
ADD COLUMN IF NOT EXISTS retried BOOLEAN NOT NULL DEFAULT FALSE;
